# branches to build
branches:
  # whitelist
  only:
    - master

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input


# clone directory
clone_folder: c:\projects\cryptominisat

platform: x64
configuration: Release

install:
  # by default, all script lines are interpreted as batch

build:
  project: INSTALL.vcxproj      # path to Visual Studio solution or project

# scripts to run before build
before_build:
  - echo Running cmake...
  - cd c:\projects\cryptominisat
  - cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX=%P%

# scripts to run after build
after_build:
  - cd %P%
  - 7z a c:\projects\cryptominisat\cryptominisat.zip * -tzip
  - cd c:\projects\cryptominisat

artifacts:
  - path: cryptominisat.zip
    name: cryptominisat.zip

deploy_script:
  #- cd c:\projects\cryptominisat
  #- curl -T cryptominisat.zip --user %ACCOUNT% https://someplace/

on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
